<?php

namespace Base;

class TextArea extends Text
{
    public function draw(?int $key): void
    {
        switch ($key) {
            case NCURSES_KEY_BACKSPACE:
                $this->text = substr($this->text, 0, -1);
                break;
            default:
                if (ctype_print($key)) {
                    $this->text .= chr($key);
                }
        }
        parent::draw($key); // TODO: Change the autogenerated stub
    }

}