<?php

namespace Base;

class TextArea extends Text
{
    /** @var Position */
    protected $cursorPosition;

    /**
     * @param int|null $key
     * @throws \Exception
     */
    public function draw(?int $key): void
    {
        switch ($key) {
            case NCURSES_KEY_BACKSPACE:
                $this->text = substr($this->text, 0, -1);
                break;
            default:
                if (ctype_print($key)) {
                    $this->text .= chr($key);
                }
        }
        parent::draw($key);
    }

    /**
     * @param Surface $surface
     * @return Text
     */
    public function setSurface(Surface $surface): Text
    {
        $this->cursorPosition = clone $surface->topLeft();
        return parent::setSurface($surface); // TODO: Change the autogenerated stub
    }
}